version: "2"
services:
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: place_dev
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"